"""empty message

Revision ID: 63804dd52f7c
Revises: c95d6ed068bb
Create Date: 2023-01-23 16:22:05.296842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63804dd52f7c'
down_revision = 'c95d6ed068bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blocked_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blocked_list')
    # ### end Alembic commands ###
